// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: siderolink/provision.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node UUID as string.
	NodeUuid string `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	// Wireguard public key (as string) of the node.
	NodePublicKey string `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	// Join token (as string) of the node.
	JoinToken *string `protobuf:"bytes,3,opt,name=join_token,json=joinToken,proto3,oneof" json:"join_token,omitempty"`
	// Unique token (as string) of the node. Needed in case node provided node_uuid with all zeroes.
	// Or two and more nodes have the same node_uuid.
	NodeUniqueToken *string `protobuf:"bytes,4,opt,name=node_unique_token,json=nodeUniqueToken,proto3,oneof" json:"node_unique_token,omitempty"`
	// Talos Version (as string) of the node.
	TalosVersion *string `protobuf:"bytes,5,opt,name=talos_version,json=talosVersion,proto3,oneof" json:"talos_version,omitempty"`
	// Wireguard over GRPC tunnel request
	WireguardOverGrpc *bool `protobuf:"varint,6,opt,name=wireguard_over_grpc,json=wireguardOverGrpc,proto3,oneof" json:"wireguard_over_grpc,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_siderolink_provision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siderolink_provision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_siderolink_provision_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionRequest) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *ProvisionRequest) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

func (x *ProvisionRequest) GetJoinToken() string {
	if x != nil && x.JoinToken != nil {
		return *x.JoinToken
	}
	return ""
}

func (x *ProvisionRequest) GetNodeUniqueToken() string {
	if x != nil && x.NodeUniqueToken != nil {
		return *x.NodeUniqueToken
	}
	return ""
}

func (x *ProvisionRequest) GetTalosVersion() string {
	if x != nil && x.TalosVersion != nil {
		return *x.TalosVersion
	}
	return ""
}

func (x *ProvisionRequest) GetWireguardOverGrpc() bool {
	if x != nil && x.WireguardOverGrpc != nil {
		return *x.WireguardOverGrpc
	}
	return false
}

type ProvisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server Wireguard endpoint IP and port.
	ServerEndpoint []string `protobuf:"bytes,1,rep,name=server_endpoint,json=serverEndpoint,proto3" json:"server_endpoint,omitempty"`
	// Server public Wireguard key encoded as string.
	ServerPublicKey string `protobuf:"bytes,3,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	// Node address with prefix on the Wireguard tunnel.
	NodeAddressPrefix string `protobuf:"bytes,4,opt,name=node_address_prefix,json=nodeAddressPrefix,proto3" json:"node_address_prefix,omitempty"`
	// Server address on the Wireguard tunnel.
	ServerAddress string `protobuf:"bytes,5,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	// Virtual peer address:port in case of Wireguard over GRPC.
	GrpcPeerAddrPort string `protobuf:"bytes,6,opt,name=grpc_peer_addr_port,json=grpcPeerAddrPort,proto3" json:"grpc_peer_addr_port,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_siderolink_provision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siderolink_provision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_siderolink_provision_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionResponse) GetServerEndpoint() []string {
	if x != nil {
		return x.ServerEndpoint
	}
	return nil
}

func (x *ProvisionResponse) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *ProvisionResponse) GetNodeAddressPrefix() string {
	if x != nil {
		return x.NodeAddressPrefix
	}
	return ""
}

func (x *ProvisionResponse) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ProvisionResponse) GetGrpcPeerAddrPort() string {
	if x != nil {
		return x.GrpcPeerAddrPort
	}
	return ""
}

var File_siderolink_provision_proto protoreflect.FileDescriptor

const file_siderolink_provision_proto_rawDesc = "" +
	"\n" +
	"\x1asiderolink/provision.proto\x12\vsidero.link\"\xda\x02\n" +
	"\x10ProvisionRequest\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\tR\rnodePublicKey\x12\"\n" +
	"\n" +
	"join_token\x18\x03 \x01(\tH\x00R\tjoinToken\x88\x01\x01\x12/\n" +
	"\x11node_unique_token\x18\x04 \x01(\tH\x01R\x0fnodeUniqueToken\x88\x01\x01\x12(\n" +
	"\rtalos_version\x18\x05 \x01(\tH\x02R\ftalosVersion\x88\x01\x01\x123\n" +
	"\x13wireguard_over_grpc\x18\x06 \x01(\bH\x03R\x11wireguardOverGrpc\x88\x01\x01B\r\n" +
	"\v_join_tokenB\x14\n" +
	"\x12_node_unique_tokenB\x10\n" +
	"\x0e_talos_versionB\x16\n" +
	"\x14_wireguard_over_grpc\"\xee\x01\n" +
	"\x11ProvisionResponse\x12'\n" +
	"\x0fserver_endpoint\x18\x01 \x03(\tR\x0eserverEndpoint\x12*\n" +
	"\x11server_public_key\x18\x03 \x01(\tR\x0fserverPublicKey\x12.\n" +
	"\x13node_address_prefix\x18\x04 \x01(\tR\x11nodeAddressPrefix\x12%\n" +
	"\x0eserver_address\x18\x05 \x01(\tR\rserverAddress\x12-\n" +
	"\x13grpc_peer_addr_port\x18\x06 \x01(\tR\x10grpcPeerAddrPort2^\n" +
	"\x10ProvisionService\x12J\n" +
	"\tProvision\x12\x1d.sidero.link.ProvisionRequest\x1a\x1e.sidero.link.ProvisionResponseB4Z2github.com/siderolabs/siderolink/api/siderolink/pbb\x06proto3"

var (
	file_siderolink_provision_proto_rawDescOnce sync.Once
	file_siderolink_provision_proto_rawDescData []byte
)

func file_siderolink_provision_proto_rawDescGZIP() []byte {
	file_siderolink_provision_proto_rawDescOnce.Do(func() {
		file_siderolink_provision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_siderolink_provision_proto_rawDesc), len(file_siderolink_provision_proto_rawDesc)))
	})
	return file_siderolink_provision_proto_rawDescData
}

var file_siderolink_provision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_siderolink_provision_proto_goTypes = []any{
	(*ProvisionRequest)(nil),  // 0: sidero.link.ProvisionRequest
	(*ProvisionResponse)(nil), // 1: sidero.link.ProvisionResponse
}
var file_siderolink_provision_proto_depIdxs = []int32{
	0, // 0: sidero.link.ProvisionService.Provision:input_type -> sidero.link.ProvisionRequest
	1, // 1: sidero.link.ProvisionService.Provision:output_type -> sidero.link.ProvisionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_siderolink_provision_proto_init() }
func file_siderolink_provision_proto_init() {
	if File_siderolink_provision_proto != nil {
		return
	}
	file_siderolink_provision_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_siderolink_provision_proto_rawDesc), len(file_siderolink_provision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_siderolink_provision_proto_goTypes,
		DependencyIndexes: file_siderolink_provision_proto_depIdxs,
		MessageInfos:      file_siderolink_provision_proto_msgTypes,
	}.Build()
	File_siderolink_provision_proto = out.File
	file_siderolink_provision_proto_goTypes = nil
	file_siderolink_provision_proto_depIdxs = nil
}
