// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: siderolink/wireguard.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerPacket is a packet sent between "server" and client.
type PeerPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerPacket) Reset() {
	*x = PeerPacket{}
	mi := &file_siderolink_wireguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerPacket) ProtoMessage() {}

func (x *PeerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_siderolink_wireguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerPacket.ProtoReflect.Descriptor instead.
func (*PeerPacket) Descriptor() ([]byte, []int) {
	return file_siderolink_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *PeerPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_siderolink_wireguard_proto protoreflect.FileDescriptor

const file_siderolink_wireguard_proto_rawDesc = "" +
	"\n" +
	"\x1asiderolink/wireguard.proto\x12\vsidero.link\" \n" +
	"\n" +
	"PeerPacket\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data2`\n" +
	"\x18WireGuardOverGRPCService\x12D\n" +
	"\fCreateStream\x12\x17.sidero.link.PeerPacket\x1a\x17.sidero.link.PeerPacket(\x010\x01B4Z2github.com/siderolabs/siderolink/api/siderolink/pbb\x06proto3"

var (
	file_siderolink_wireguard_proto_rawDescOnce sync.Once
	file_siderolink_wireguard_proto_rawDescData []byte
)

func file_siderolink_wireguard_proto_rawDescGZIP() []byte {
	file_siderolink_wireguard_proto_rawDescOnce.Do(func() {
		file_siderolink_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_siderolink_wireguard_proto_rawDesc), len(file_siderolink_wireguard_proto_rawDesc)))
	})
	return file_siderolink_wireguard_proto_rawDescData
}

var file_siderolink_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_siderolink_wireguard_proto_goTypes = []any{
	(*PeerPacket)(nil), // 0: sidero.link.PeerPacket
}
var file_siderolink_wireguard_proto_depIdxs = []int32{
	0, // 0: sidero.link.WireGuardOverGRPCService.CreateStream:input_type -> sidero.link.PeerPacket
	0, // 1: sidero.link.WireGuardOverGRPCService.CreateStream:output_type -> sidero.link.PeerPacket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_siderolink_wireguard_proto_init() }
func file_siderolink_wireguard_proto_init() {
	if File_siderolink_wireguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_siderolink_wireguard_proto_rawDesc), len(file_siderolink_wireguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_siderolink_wireguard_proto_goTypes,
		DependencyIndexes: file_siderolink_wireguard_proto_depIdxs,
		MessageInfos:      file_siderolink_wireguard_proto_msgTypes,
	}.Build()
	File_siderolink_wireguard_proto = out.File
	file_siderolink_wireguard_proto_goTypes = nil
	file_siderolink_wireguard_proto_depIdxs = nil
}
